Add LUX - LUXFILM - Update facilities.json
ISDCF/registries pull request #1026
Opened 2024-12-24 14:18 UTC by japierce1028

Opt IN
The request says there is an obsoleted code "LUXF" but it doesn't and couldn't exist in the pre-4 character world. So I'm ignoring it. Then they listed the name as LUXFILM OÜ but the website lists it as just LUXFILM so I removed the two characters.

2024-12-24 23:16 UTC, palemieux commented
@japierce1028 "The most common forms of business in Estonia are private limited company (OÜ), public limited company (AS) and sole proprietor (FIE)."

https://www.eesti.ee/en/doing-business/establishing-a-company/comparison-of-each-form-of-business/#:~:text=The%20most%20common%20forms%20of,and%20sole%20proprietor%20(FIE).

2024-12-24 23:17 UTC, palemieux requested changes
I think OÜ might be right

2025-01-16 20:57 UTC, japierce1028 commented
Will do. Added LUXFILM OÜ

2025-01-17 00:37 UTC, palemieux approved these changes

2025-01-17 00:39 UTC, palemieux approved these changes

2025-01-17 00:39 UTC, merged