Add HULU studio code
ISDCF/registries pull request #183
Opened 2021-05-04 23:25 UTC by radford-for-smpte

2021-05-04 23:27 UTC, SteveLLamb approved these changes

2021-05-05 03:08 UTC, palemieux requested changes
@radford-for-smpte No contact information?

2021-05-05 03:41 UTC, radford-for-smpte commented
closes #183

2021-05-05 03:46 UTC, palemieux approved these changes

2021-05-05 03:48 UTC, merged