Add TK - TECNOKENA
ISDCF/registries pull request #277
Opened 2021-10-15 00:56 UTC by japierce1028

Opt IN - URL doesn't resolve. I'll send an email questioning, but we should go ahead and add it (I assume they will have https)

2021-10-21 15:54 UTC, palemieux requested changes
URL does not resolve

2021-11-15 14:47 UTC, palemieux requested changes

2021-11-15 14:47 UTC, palemieux commented on src/main/data/studios.json
> +    "url": "https://www.tecnokena.com.br"
```suggestion
    "url": "http://www.tecnokena.com.br"
```

2021-11-15 14:49 UTC, palemieux commented
@japierce1028 It looks like `https` does not work. I suggest changing it to `http`, ok?

2021-11-15 15:26 UTC, japierce1028 commented
Seems right to me...

2021-11-15 15:29 UTC, japierce1028 commented
Looks like I can't commit. Only close.

2021-11-15 15:40 UTC, palemieux approved these changes

2021-11-15 15:41 UTC, merged