Add FC - Flying Cloud Productions Inc.
ISDCF/registries pull request #313
Opened 2022-01-11 15:38 UTC by japierce1028

Opt IN

2022-01-11 16:20 UTC, palemieux approved these changes

2022-01-11 16:21 UTC, palemieux requested changes

2022-01-11 16:21 UTC, palemieux commented on src/main/data/studios.json
> +      "address": "111- 618 East Kent Avenue S. Vancouver BC V5X 0B1, Canada",
```suggestion
      "address": "111-618 East Kent Avenue S. Vancouver BC V5X 0B1, Canada",
```

2022-01-11 16:21 UTC, palemieux commented
@japierce1028 See typo.

2022-01-11 20:01 UTC, palemieux approved these changes

2022-01-20 23:53 UTC, SteveLLamb commented
Was this Ok'd to go and left for some reason?

2022-01-20 23:57 UTC, merged