Update ATMOS as legacy - audio configs
ISDCF/registries pull request #524
Opened 2022-12-08 17:24 UTC by SteveLLamb

Closes #438 

As noted in the above issue, permission has now been granted by a studio for an exhibitor to service IAB Profile 1 for DTSX equipment. ATMOS has been marked as "Legacy" in the notes.

2022-12-08 17:28 UTC, SteveLLamb commented
FYI, no change to Illustrated Guide is needed.

2022-12-19 18:18 UTC, palemieux requested changes

2023-01-03 21:29 UTC, palemieux commented
@SteveLLamb Ping

2023-01-06 16:30 UTC, SteveLLamb commented on src/main/data/audioconfigs.json
> +    "note": "Legacy, replaced by Immersive Audio Bitstream (SMPTE ST2098-2) Profile 1"
Updated in https://github.com/ISDCF/registries/pull/524/commits/ecce4497c96b41e819d48042a4c4a468f4d40616. Full description added parenthetically, to help eliminate questions (I have to answer "what is IAB" on a weekly basis).

2023-01-06 16:40 UTC, palemieux commented on src/main/data/audioconfigs.json
> +    "note": "Legacy. IAB [Immersive Audio Bitstream (SMPTE ST2098-2) Profile 1] should be used instead."
```suggestion
    "note": "Deprecated. The IAB label should be used instead."
```

2023-01-06 16:40 UTC, palemieux approved these changes

2023-01-06 16:47 UTC, merged