Add FGSC - Feirstein Graduate School of Cinema
ISDCF/registries pull request #571
Opened 2023-02-26 15:44 UTC by japierce1028

Opt IN

2023-03-02 16:06 UTC, palemieux requested changes

2023-03-02 16:06 UTC, palemieux commented on src/main/data/studios.json
> +    "url": "https://feirstein.brooklyn.cuny.edu/m"
URL has an errant `m` at the end.

2023-03-04 15:13 UTC, japierce1028 commented
oops. Fixed.

2023-03-04 16:04 UTC, palemieux approved these changes

2023-03-04 16:06 UTC, merged