Add Terms Registry
ISDCF/registries pull request #586
Opened 2023-04-03 22:45 UTC by SteveLLamb

First pass on terms registry as per AI at prior ISDCF meeting. 

Let's focus this round of PR solely on the structure of the data, while future PR(s) can focus on updating the actual Terms, their definitions, and other field related to the Terms themselves.

After this PR is merged, will work on adding to the DCNC. But also, ICTA (or others) may use this registry as they need on their own websites pulling from the API here.

2023-04-03 22:49 UTC, palemieux requested changes
Need to validate the URLs like at https://github.com/ISDCF/registries/blob/a92370b45a788aaac8bf59c5add1830f9c7ad09d/src/main/scripts/studios.validate.js#L39

2023-04-03 22:49 UTC, SteveLLamb commented
One note, a thing I'm thinking to the validation, is that "relatedTerms" must be present present in the registry as a Term.

2023-04-05 15:57 UTC, SteveLLamb commented
> Need to validate the URLs like at
> 
> > https://github.com/ISDCF/registries/blob/a92370b45a788aaac8bf59c5add1830f9c7ad09d/src/main/scripts/studios.validate.js#L39

@palemieux see https://github.com/ISDCF/registries/pull/586/commits/4650502890efc3a600916a9bdb0321d1f8d43653

2023-04-05 16:28 UTC, SteveLLamb commented
> One note, a thing I'm thinking to the validation, is that "relatedTerms" must be present present in the registry as a Term.

addressed in https://github.com/ISDCF/registries/pull/586/commits/a76c03c8af28e9a70d49b372ad6c25e20561ddf8

2023-04-05 18:42 UTC, SteveLLamb commented on src/main/scripts/terms.validate.js
> +        console.log(name + " registry term '" + registry[r].term + "' contains relatedTerm '" + relatedTerm[rT] + "' that is not a defined term");
changing this to a `throw` causes build to fail

2023-04-05 18:44 UTC, SteveLLamb commented on src/main/scripts/terms.validate.js
> +        console.log(name + " registry term '" + registry[r].term + "' contains relatedTerm '" + relatedTerm[rT] + "' that is not a defined term");
was trying this:
`throw `${name} registry term '${registry[r].term}' contains relatedTerm '${relatedTerm[r]}' that is not a defined term`;`

2023-04-05 19:05 UTC, SteveLLamb commented on src/main/scripts/terms.validate.js
> +        console.log(name + " registry term '" + registry[r].term + "' contains relatedTerm '" + relatedTerm[rT] + "' that is not a defined term");
@palemieux disregard. Got it!

2023-04-05 19:06 UTC, SteveLLamb commented
> One note, a thing I'm thinking to the validation, is that "relatedTerms" must be present present in the registry as a Term.

Done in https://github.com/ISDCF/registries/pull/586/commits/b63c868ea01b327068905993a9135e09df07a133

2023-06-05 18:08 UTC, palemieux approved these changes

2023-06-05 18:16 UTC, SteveLLamb commented
To be merged after June 15th meeting if no objections.

2023-06-15 20:23 UTC, merged