Add Facility AST
ISDCF/registries pull request #642
Opened 2023-06-09 04:54 UTC by ygonno

Opt Out:

Below is the full description:

  {
    "code": "AST",
    "contact": {
      "address": "4-16-7 Nishi-Kohjiya Ohta-ku Tokyo, Japan",
      "email": "itou@assist-corp.com",
      "name": "Takemasa Ito"
    },
    "description": "Assist corp."
    "url": "https://www.assist-corp.tv/"
  },

2023-06-10 11:04 UTC, ygonno commented
Did I miss something? I don't understand what is causing such validation failures.

2023-06-10 16:00 UTC, palemieux requested changes

2023-06-10 16:00 UTC, palemieux commented on src/main/data/facilities.json
> +    "description": "Assist corp."
Comma `,` missing

2023-06-10 17:24 UTC, ygonno commented
argh.. my eyes.. thx!

2023-06-10 18:16 UTC, palemieux commented
@japierce1028 For your review

2023-06-10 18:36 UTC, palemieux commented
@ygonno Can you merge in the latest HEAD of `master` branch?

2023-06-10 18:52 UTC, ygonno commented
Done?

2023-06-10 22:23 UTC, palemieux approved these changes

2023-06-10 22:24 UTC, palemieux commented
@ygonno It looks good technically. @japierce1028 should review for content.

2023-06-11 13:35 UTC, japierce1028 approved these changes
I assume this came directly and not through the google form submission. In one comment it says "Opt OUT" so the final entry only shows the URL, so seems right to me.

2023-06-11 13:39 UTC, japierce1028 commented
Wait, when I go to "squash and merge" it shows all the entries. Clearly I don't know what I'm doing. It should ONLY have the name, description and URL -- assuming it is an Opt OUT entry.

2023-06-11 17:09 UTC, palemieux commented
> Wait, when I go to "squash and merge" it shows all the entries. Clearly I don't know what I'm doing. It should ONLY have the name, description and URL -- assuming it is an Opt OUT entry.

@japierce1028 You should edit the commit message to remove all irrelevant information.

![image](https://github.com/ISDCF/registries/assets/4871350/00c03d27-b5f8-4548-981c-2b9109930e0f)

2023-06-11 20:54 UTC, merged

2023-06-11 20:54 UTC, japierce1028 commented
When I go to ygonno:patch-1 all seems right (only the correct info). So I went ahead and confirmed the merger.