Add TFN - THE FIN - Update facilities.json
ISDCF/registries pull request #822
Opened 2024-02-22 16:46 UTC by japierce1028

via email addition of this facility and the obsolete of SNU. I have asked for entry in our form.

2024-02-29 23:56 UTC, palemieux commented
@japierce1028 What is the obsolete code?

2024-02-29 23:57 UTC, palemieux requested changes
Obsolete code missing

2024-03-01 21:40 UTC, japierce1028 commented
The email is below. I have asked twice for them to submit via the on-line form, but so far no response. I figure we should add the new code now and not obsolete SNU until we hear back.

Begin forwarded message:

From: 이승우 <kammy0328@naver.com>
Subject: Request for ISDCF Facility Change / SNU
Date: February 18, 2024 at 11:43:05 PM MST
To: <digitalcinemanaming@isdcf.com>

Dear ISDCF Team,

I am writing to request a change of facility codes in the ISDCF system for the following institutions:

[CODES]
From: SNU
To: TFN

[DESCRIPTION]
From: SUNURI
To: THE FIN

[CONTACT INFO]
From: 15, Moraenae-Ro 7an-Gil, Mapo-Gu, Seoul, Republic Of Korea
To: 37-15, Mokdongjungangbon-ro 7-gil, Yangcheon-gu, Seoul, Republic of Korea

From: [sunuriofficial@gmail.com](mailto:sunuriofficial@gmail.com)
To: [kammy0328@naver.com](mailto:kammy0328@naver.com)

Please let me know if you have any questions or require additional information.

Sincerely,
Lee Seung Woo

2024-03-01 22:29 UTC, palemieux approved these changes

2024-03-01 22:30 UTC, merged