Update SEA - 950 E 3rd St. Los Angeles 90013, USA - Update facilities…
ISDCF/registries pull request #834
Opened 2024-03-14 14:27 UTC by japierce1028

….json

This was an update request to change to Sayonse as name of facility.

2024-03-19 14:47 UTC, palemieux requested changes
I am not excited by the idea of dramatically changing the name of the studios and keeping the code intact since I expect most folks to connect one with the other.

2024-03-19 14:47 UTC, palemieux commented on src/main/data/facilities.json
> +      "address": "950 E 3rd St. Los Angeles 90013, USA",
```suggestion
      "address": "950 E 3rd St., Los Angeles 90013, USA",
```

2024-03-20 23:03 UTC, japierce1028 commented
I’m OK with it if it is the same location and people. I assume they would want to be able to track down who made a DCP and if it’s the same organization seems OK with a name change. A new location? That’s a different code if they also change their name.

2024-03-21 00:12 UTC, palemieux approved these changes

2024-03-21 00:14 UTC, merged