Add H18 - Hangar 18 Media  - Update studios.json
ISDCF/registries pull request #867
Opened 2024-04-19 13:36 UTC by japierce1028

Opt IN

2024-04-19 22:29 UTC, palemieux requested changes

2024-04-19 22:29 UTC, palemieux commented on src/main/data/studios.json
> +      "address": "5025 Orbitor Drive, Building 4, Unit 301, Mississauga, ON L4W4Y5, Canada",
```suggestion
      "address": "5025 Orbitor Drive, Building 4, Unit 301, Mississauga, ON L4W 4Y5, Canada",
```

2024-05-16 13:32 UTC, japierce1028 reviewed
Yep, looks better.

2024-05-16 16:06 UTC, palemieux approved these changes

2024-05-16 16:06 UTC, palemieux approved these changes

2024-05-16 16:06 UTC, merged