Add M5 - Mesa5 Producciones - Update studios.json
ISDCF/registries pull request #868
Opened 2024-04-19 13:39 UTC by japierce1028

Opt IN

2024-04-19 22:31 UTC, palemieux requested changes

2024-04-19 22:31 UTC, palemieux commented on src/main/data/studios.json
> +      "address": "Calle Maestro Arbós 3, oficina 109, 28019, Madrid, Spain",
```suggestion
      "address": "Calle Maestro Arbós 3, oficina 109, 28019,Madrid, Spain",
```

2024-05-16 13:33 UTC, japierce1028 reviewed
Looks good

2024-05-16 16:07 UTC, palemieux approved these changes

2024-05-16 16:08 UTC, merged