Add KTT - KILL THE TAPE - Update facilities.json
ISDCF/registries pull request #886
Opened 2024-05-18 22:12 UTC by japierce1028

Opt IN. -- will need to obsolete DC after this gets entered.

2024-05-19 16:51 UTC, palemieux commented
@japierce1028 Why not include the obsolescence step in this pull request?

2024-05-19 21:22 UTC, japierce1028 commented
Last time I did it as two separate Pull requests and it bounced since the "replaced by" didn't exist. If they are both in the same request would it work? Is that a good idea to have them together?

2024-05-19 21:49 UTC, palemieux commented
> Last time I did it as two separate Pull requests and it bounced since the "replaced by" didn't exist. If they are both in the same request would it work? Is that a good idea to have them together? 

It is a good idea to have them together.

2024-05-19 23:03 UTC, japierce1028 commented
Added the obsolete and it failed, but I can't tell why.

2024-05-20 07:47 UTC, palemieux requested changes

2024-05-20 07:47 UTC, palemieux commented on src/main/data/facilities.json
> +    ],
```suggestion
    ]
```

Extra comma :)

2024-05-20 07:48 UTC, palemieux commented
> Added the obsolete and it failed, but I can't tell why.

Extra comma :)

2024-05-20 13:13 UTC, japierce1028 commented
So many commas, so little time.

2024-05-20 14:14 UTC, palemieux approved these changes

2024-05-20 14:15 UTC, merged