Add 3CAT - TV3, 3Cat:  Is the public TV from Catalonia (Spain)  - Upd…
ISDCF/registries pull request #899
Opened 2024-06-17 17:45 UTC by japierce1028

…ate studios.json

Opt IN

2024-06-17 18:06 UTC, palemieux requested changes

2024-06-17 18:06 UTC, palemieux commented on src/main/data/studios.json
> +      "address": "Carrer Oriol Martorell, 1 Sant Joan Despí, Barcelona, Spain",
ZIP code is missing

2024-06-18 13:19 UTC, japierce1028 commented on src/main/data/studios.json
> +      "address": "Carrer Oriol Martorell, 1 Sant Joan Despí, Barcelona, Spain",
I think I added it...

2024-06-18 15:21 UTC, palemieux approved these changes

2024-06-18 15:22 UTC, merged